apiVersion: v2
appVersion: 10.11.7
description: A Helm chart for MariaDB on Kubernetes
icon: https://mariadb.com/wp-content/uploads/2019/11/mariadb-logo_black-transparent-600x150.png
keywords:
- database
- mariadb
maintainers:
- name: groundhog2k
  url: https://github.com/groundhog2k/helm-charts
name: mariadb
type: application
version: 3.1.0
